dataset_id : "COCO"
file_list_path: "datasets/COCO/lists/train_data_list.txt" # list containing the path to the images and the annotations
base_path: "datasets/COCO" # path to the dataset folder, concatenates with the paths in the list if not empty
output_folder: "/mnt/train_output" # path to save the output files
checkpoints: # absolute path to checkpoint
num_classes_checkpoint: 201 #classes used for training the checkpoint

num_classes: 81 #with background

batch_size: 32
lr : 0.001
weight_decay: 0.005
epochs: 200
workers: 4
num_checkpoints: 3 # number of checkpoints to save during training

scheduler:
  name: "cosine"
  warmup_epochs: 5
  base_lr: 1.25e-3 # 4096 batch-size
  warmup_lr: 1.25e-6
  min_lr: 1.25e-5

model:
  id: "FPNSwin2Small-224"
  freeze_decoder: False
  freeze_encoder: False


