dataset_id : "ILSVRC2017-COCO"
file_list_path: "/mnt/datasets/COCO/lists/train_data_list.txt"
base_path: "/mnt/datasets/COCO"
output_folder: "/mnt/train_output"
checkpoints: '/mnt/train_output/ILSVRC2017/checkpoints/ILSVRC2017_FPNVitHuge-224_best_model.pth' # absolute path to checkpoint
num_classes_checkpoint: 201 #classes used for training the checkpoint

num_classes: 81 #with background

batch_size: 32
lr : 1.25e-5 # 1.25e-4 , 1.25e-5
weight_decay: 1.0e-8 # 1.0e-7 , 1.0e-8
epochs: 50 # 25 , 50
workers: 4
num_checkpoints: 3

scheduler: 

model:
  id: "FPNVitHuge-224"
  freeze_decoder: False
  freeze_encoder: False


